# Generated by Django 5.0.7 on 2024-08-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=20)),
                ('hostel_type', models.CharField(choices=[('BOYS', 'boys'), ('GIRLS', 'girls')], max_length=5)),
                ('main_location', models.CharField(choices=[('KATHMANDU', 'kathmandu'), ('BHAKTAPUR', 'bhaktapur'), ('LALITPUR', 'lalitpur')], max_length=15)),
                ('sec_location', models.CharField(max_length=15)),
                ('hostel_description', models.TextField(max_length=1000)),
                ('hostel_contact_number', models.IntegerField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
