# Generated by Django 5.0.7 on 2024-08-12 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hostel_hostel_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
            preserve_default=False,
        ),
    ]
